-- COLUMN
ALTER TABLE SYS_OFFICE ADD IS_SHOW VARCHAR2(2);
COMMENT ON COLUMN SYS_OFFICE.IS_SHOW IS '是否启用:01-启用;99-停用';
ALTER TABLE SYS_OFFICE RENAME COLUMN IS_SHOW TO IS_SHOW2;
ALTER TABLE SYS_OFFICE MODIFY IS_SHOW VARCHAR2(200);
ALTER TABLE SYS_OFFICE DROP COLUMN IS_SHOW;

-- INDEX/CONSTRAINTS
CREATE INDEX IDX_SYS_OFFICE_ID ON SYS_OFFICE (ID);

ALTER TABLE SYS_OFFICE ADD CONSTRAINTS PK_SYS_OFFICE_ID PRIMARY KEY (ID);
ALTER TABLE SYS_OFFICE DROP CONSTRAINTS PK_SYS_OFFICE_ID CASCADE;