-- COLUMN
ALTER TABLE SYS_OFFICE ADD IS_SHOW VARCHAR2(2);
COMMENT ON COLUMN SYS_OFFICE.IS_SHOW IS '是否启用:01-启用;99-停用';
ALTER TABLE SYS_OFFICE RENAME COLUMN IS_SHOW TO IS_SHOW2;
ALTER TABLE SYS_OFFICE MODIFY IS_SHOW VARCHAR2(200);
ALTER TABLE SYS_OFFICE DROP COLUMN IS_SHOW;