CREATE TABLESPACE T_SHAWN
  logging
datafile  '/u01/app/oracle/oradata/XE/T_SHAWN.dbf'
  size 200m
  autoextend on
next 200m maxsize 2048m
  extent management local
;


-- DROP TABLESPACE T_SHAWN INCLUDING CONTENTS AND DATAFILES;


CREATE USER SHAWN
  IDENTIFIED BY "SHAWN"
DEFAULT TABLESPACE T_SHAWN
-- QUOTA 50M ON USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO SHAWN;
GRANT RESOURCE TO SHAWN;
GRANT CREATE SEQUENCE TO SHAWN;
GRANT CREATE VIEW TO SHAWN;
-- GRANT CREATE SESSION TO SHAWN;
-- GRANT CREATE TABLE TO SHAWN;
-- GRANT CREATE PROCEDURE TO SHAWN;

-- DROP USER SHAWN CASCADE;

