-- 查看SYS用户下object_type为TABLE的对象
SELECT OWNER,COUNT(*)
FROM DBA_OBJECTS
WHERE OBJECT_TYPE='TABLE' AND OWNER='SYS'
GROUP BY OWNER;

-- 查看DBA_TABLES中owner为sys的表
SELECT OWNER,COUNT(*)
FROM DBA_TABLES
WHERE OWNER='SYS'
GROUP BY OWNER;

-- 对象表
-- 使用SYS用户查看
SELECT *
FROM USER_OBJECT_TABLES;